const formElementsType = {
  autocomplete: {
    AutocompleteAsynchronousRequest: "AutocompleteAsynchronousRequest",
    AutocompleteCheckboxes: "AutocompleteCheckboxes",
    AutocompleteControlledUncontrolled: "AutocompleteControlledUncontrolled",
    AutocompleteCountry: "AutocompleteCountry",
    AutocompleteCreatable: "AutocompleteCreatable",
    AutocompleteCustomFilter: "AutocompleteCustomFilter",
    AutocompleteCustomInput: "AutocompleteCustomInput",
    AutocompleteDisabledOptions: "AutocompleteDisabledOptions",
    AutocompleteFixedOptions: "AutocompleteFixedOptions",
    AutocompleteFreeSolo: "AutocompleteFreeSolo",
    AutocompleteGrouped: "AutocompleteGrouped",
    AutocompleteLimitTags: "AutocompleteLimitTags",
    AutocompleteMultipleValues: "AutocompleteMultipleValues",
    AutocompleteProps: "AutocompleteProps",
    AutocompleteSmallSize: "AutocompleteSmallSize",
    AutocompleteSourceCode: "AutocompleteSourceCode",
    AutocompleteVariants: "AutocompleteVariants",
  },
  checkbox: {
    CheckboxesBasic: "CheckboxesBasic",
    CheckboxesColors: "CheckboxesColors",
    CheckboxesControlledUncontrolled: "CheckboxesControlledUncontrolled",
    CheckboxesCustomIcons: "CheckboxesCustomIcons",
    CheckboxesCustomized: "CheckboxesCustomized",
    CheckboxesLabelPlacement: "CheckboxesLabelPlacement",
    CheckboxesShowError: "CheckboxesShowError",
    CheckboxesSizes: "CheckboxesSizes",
    CheckboxesSourceCode: "CheckboxesSourceCode",
  },
  "custom-inputs": {
    CustomCheckboxBasic: "CustomCheckboxBasic",
    CustomCheckboxIcons: "CustomCheckboxIcons",
    CustomCheckboxImg: "CustomCheckboxImg",
    CustomInputsSourceCode: "CustomInputsSourceCode",
    CustomRadioBasic: "CustomRadioBasic",
    CustomRadioIcons: "CustomRadioIcons",
    CustomRadioImg: "CustomRadioImg",
  },
  editor: {
    EditorControlled: "EditorControlled",
    EditorSourceCode: "EditorSourceCode",
    EditorUncontrolled: "EditorUncontrolled",
  },
  "file-uploader": {
    FileUploaderMultiple: "FileUploaderMultiple",
    FileUploaderRestrictions: "FileUploaderRestrictions",
    FileUploaderSingle: "FileUploaderSingle",
    FileUploaderSourceCode: "FileUploaderSourceCode",
  },
  "input-mask": {
    InputMaskExamples: "InputMaskExamples",
    InputMaskSourceCode: "InputMaskSourceCode",
  },
  pickers: {
    PickersBasic: "PickersBasic",
    PickersCallbacks: "PickersCallbacks",
    PickersCustomInput: "PickersCustomInput",
    PickersCustomization: "PickersCustomization",
    PickersIncludeExclude: "PickersIncludeExclude",
    PickersLocale: "PickersLocale",
    PickersMinMax: "PickersMinMax",
    PickersMonthYearDropdowns: "PickersMonthYearDropdowns",
    PickersMonthYearQuarter: "PickersMonthYearQuarter",
    PickersOptions: "PickersOptions",
    PickersRange: "PickersRange",
    PickersSourceCode: "PickersSourceCode",
    PickersSpecificRange: "PickersSpecificRange",
    PickersTime: "PickersTime",
  },
  radio: {
    RadioColor: "RadioColor",
    RadioControlledUncontrolled: "RadioControlledUncontrolled",
    RadioCustomized: "RadioCustomized",
    RadioGroup: "RadioGroup",
    RadioLabelPlacement: "RadioLabelPlacement",
    RadioShowError: "RadioShowError",
    RadioSizes: "RadioSizes",
    RadioSourceCode: "RadioSourceCode",
    RadioStandalone: "RadioStandalone",
  },
  select: {
    SelectControlledUncontrolled: "SelectControlledUncontrolled",
    SelectCustomized: "SelectCustomized",
    SelectGrouping: "SelectGrouping",
    SelectMultiple: "SelectMultiple",
    SelectNative: "SelectNative",
    SelectProps: "SelectProps",
    SelectSourceCode: "SelectSourceCode",
    SelectVariants: "SelectVariants",
    SelectWithDialog: "SelectWithDialog",
  },
  slider: {
    SliderBasic: "SliderBasic",
    SliderColors: "SliderColors",
    SliderControlledUncontrolled: "SliderControlledUncontrolled",
    SliderCustomColors: "SliderCustomColors",
    SliderCustomMarks: "SliderCustomMarks",
    SliderCustomized: "SliderCustomized",
    SliderDiscrete: "SliderDiscrete",
    SliderInvertedTrack: "SliderInvertedTrack",
    SliderLabelAlwaysVisible: "SliderLabelAlwaysVisible",
    SliderMinimumDistance: "SliderMinimumDistance",
    SliderRange: "SliderRange",
    SliderRemovedTrack: "SliderRemovedTrack",
    SliderRestrictedValues: "SliderRestrictedValues",
    SliderSizes: "SliderSizes",
    SliderSmallSteps: "SliderSmallSteps",
    SliderSourceCode: "SliderSourceCode",
    SliderVertical: "SliderVertical",
  },
  switch: {
    SwitchesBasic: "SwitchesBasic",
    SwitchesColors: "SwitchesColors",
    SwitchesControlledUncontrolled: "SwitchesControlledUncontrolled",
    SwitchesCustomized: "SwitchesCustomized",
    SwitchesLabelPlacement: "SwitchesLabelPlacement",
    SwitchesSizes: "SwitchesSizes",
    SwitchesSourceCode: "SwitchesSourceCode",
    SwitchesStandalone: "SwitchesStandalone",
  },
  "text-field": {
    TextFieldColor: "TextFieldColor",
    TextFieldComponents: "TextFieldComponents",
    TextFieldControlledUncontrolled: "TextFieldControlledUncontrolled",
    TextFieldCustomized: "TextFieldCustomized",
    TextFieldFormProps: "TextFieldFormProps",
    TextFieldIcons: "TextFieldIcons",
    TextFieldInputAdornment: "TextFieldInputAdornment",
    TextFieldInputs: "TextFieldInputs",
    TextFieldLayout: "TextFieldLayout",
    TextFieldSizes: "TextFieldSizes",
    TextFieldSourceCode: "TextFieldSourceCode",
    TextFieldValidation: "TextFieldValidation",
    TextFieldVariant: "TextFieldVariant",
  },
  textarea: {
    TextareaBasic: "TextareaBasic",
    TextareaSourceCode: "TextareaSourceCode",
    TextareaVariant: "TextareaVariant",
  },
};
export default formElementsType;
